export const ADD_PAY_CHECK = "ADD_PAY_CHECK";
export const REMOVE_PAY_CHECK = "REMOVE_PAY_CHECK";
export const EDIT_PAY_CHECK = "EDIT_PAY_CHECK";
export const FETCH_SAVED_PAYCHECKS = "FETCH_SAVED_PAYCHECKS";
export const REQUEST_SAVED_PAYCHECKS = "REQUEST_SAVED_PAYCHECKS";
export  const RECIEVE_SAVED_PAYCHECKS = "RECIEVE_SAVED_PAYCHECKS";
